### PR TITLE
chore: tx-helper zombie net integration test

### PR DESCRIPTION
**Pull request by ryanleecode**
Integration tests for tx-helper

### CODE REVIEW

**Comment by ryanleecode** [comment]
@wirednkod how do i fund accounts using the `test.toml` file? I have the equivalent of ALICE and BOB in ED25519 but they don't have any funds.

**Comment by josepot** [comment]
> I have the equivalent of ALICE and BOB in ED25519 but they don't have any funds.

When you mention "the equivalent of ALICE and BOB in ED25519," it's a bit of a head-scratcher. Typically, ALICE and BOB are names we use in crypto to represent two communicating parties. If you're talking about their private keys, they'd produce different public keys in systems like ED25519 or SR25519.

To have an ED25519 equivalent of ALICE and BOB from another system like SR25519 means you've found a private key in one that matches a public key in another. That's a huge deal! If someone really managed that, it'd be a major shake-up in the cryptographic community. And, just for fun, if you actually did that, a lot of ppl (including me) might be looking for a new gig soon! 😜

**Comment by wirednkod** [comment]
I am a bit confused myself 🤔

**Comment by wirednkod** [comment]
These accounts will not be the same, as the default set Alice and Bob as the keys are different. You can always though create these accounts, and since their addresses are "known", either add the account to the genesis config with some balance or can transfer some balance from another account (e.g. the actual Alice) with an api call (which makes it also a nice integration test)

**Comment by ryanleecode** [comment]
Yes that is correct they are tottally separate accounts. Just from subkey POV they are named the same.

How would i go about setting up the genesis config?

**Comment by ryanleecode** [comment]
To clarify, in substrate for each signing scheme there is a known "Alice and "Bob", so when i say the equivalent I mean this.



```sh
# substrate key inspect --scheme Sr25519 //Alice
Secret Key URI `//Alice` is account:
  Network ID:        substrate 
 Secret seed:       0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a
  Public key (hex):  0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d
  Account ID:        0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d
  Public key (SS58): 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
  SS58 Address:      5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY

```

```sh
# substrate key inspect --scheme Sr25519 //Bob 
Secret Key URI `//Bob` is account:
  Network ID:        substrate 
 Secret seed:       0x398f0c28f98885e046333d4a41c19cee4c37368a9832c6502f6cfd182e2aef89
  Public key (hex):  0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48
  Account ID:        0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48
  Public key (SS58): 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
  SS58 Address:      5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
```

```sh
#  substrate key inspect --scheme Ed25519 //Alice
Secret Key URI `//Alice` is account:
  Network ID:        substrate 
 Secret seed:       0xabf8e5bdbe30c65656c0a3cbd181ff8a56294a69dfedd27982aace4a76909115
  Public key (hex):  0x88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee
  Account ID:        0x88dc3417d5058ec4b4503e0c12ea1a0a89be200fe98922423d4334014fa6b0ee
  Public key (SS58): 5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu
  SS58 Address:      5FA9nQDVg267DEd8m1ZypXLBnvN7SFxYwV7ndqSYGiN9TTpu

```

```sh
# substrate key inspect --scheme Ed25519 //Bob
Secret Key URI `//Bob` is account:
  Network ID:        substrate 
 Secret seed:       0x3b7b60af2abcd57ba401ab398f84f4ca54bd6b2140d2503fbcf3286535fe3ff1
  Public key (hex):  0xd17c2d7823ebf260fd138f2d7e27d114c0145d968b5ff5006125f2414fadae69
  Account ID:        0xd17c2d7823ebf260fd138f2d7e27d114c0145d968b5ff5006125f2414fadae69
  Public key (SS58): 5GoNkf6WdbxCFnPdAnYYQyCjAKPJgLNxXwPjwTh6DGg6gN3E
  SS58 Address:      5GoNkf6WdbxCFnPdAnYYQyCjAKPJgLNxXwPjwTh6DGg6gN3E
```

**Comment by ryanleecode** [comment]
Works now but ECDSA is giving me this

```
Signing Type: Ecdsa, Is Mortal: false, From: 0x020a1091341fe5664bfa1782d5e04779689068c916b04cb365ec3153755684d9a1, To: 5DVskgSC9ncWQpxFMeUn45NU43RUq93ByEge6ApbnLk6BR9N

 Error running script: ./0001-check-tx.ts        Error while executing Wasm VM: wasm `unreachable` instruction executed
"panicked at 'Bad input data provided to account_nonce: Codec error', /builds/polkadot/runtime/rococo/src/lib.rs:1650:1\n"
```

**Comment by wirednkod** [comment]
> Works now but ECDSA is giving me this
> 
> ```
> Signing Type: Ecdsa, Is Mortal: false, From: 0x020a1091341fe5664bfa1782d5e04779689068c916b04cb365ec3153755684d9a1, To: 5DVskgSC9ncWQpxFMeUn45NU43RUq93ByEge6ApbnLk6BR9N
> 
>  Error running script: ./0001-check-tx.ts        Error while executing Wasm VM: wasm `unreachable` instruction executed
> "panicked at 'Bad input data provided to account_nonce: Codec error', /builds/polkadot/runtime/rococo/src/lib.rs:1650:1\n"
> ```

This is not a Zombienet issue (I already tested next version of Zombienet and Polkadot-SDK and error remains the same). Maybe [this](https://github.com/centrifuge/go-substrate-rpc-client/issues/276#issuecomment-1182502102) will help?

**Comment by ryanleecode** [comment]
> > Works now but ECDSA is giving me this
> > ```
> > Signing Type: Ecdsa, Is Mortal: false, From: 0x020a1091341fe5664bfa1782d5e04779689068c916b04cb365ec3153755684d9a1, To: 5DVskgSC9ncWQpxFMeUn45NU43RUq93ByEge6ApbnLk6BR9N
> > 
> >  Error running script: ./0001-check-tx.ts        Error while executing Wasm VM: wasm `unreachable` instruction executed
> > "panicked at 'Bad input data provided to account_nonce: Codec error', /builds/polkadot/runtime/rococo/src/lib.rs:1650:1\n"
> > ```
> 
> This is not a Zombienet issue (I already tested next version of Zombienet and Polkadot-SDK and error remains the same). Maybe [this](https://github.com/centrifuge/go-substrate-rpc-client/issues/276#issuecomment-1182502102) will help?

We figured it out it was because when we check the nonce it expects a public key of 32 bytes but ecdsa pub keys are 33 bytes

**Review by josepot — APPROVED** [review]

**Pull request merged**
