### PR TITLE
Decode viewer

### PR DESCRIPTION
**Pull request by wirednkod**
Hey @josepot,

Last time we talked, you told me that you wanted something like this for proving how the decoder of PAPI worked.
I found it super nice and fun project, and implemented it as a side-project. 

Of course this is the very first draft (see previews below)

It contains storybook (`pnpm run storybook`) and a sample app for decoding the hex (`pnpm run dev`)

What is still missing is:

- [ ] Test more decoded scenarios and cover cases
- [ ] Beautify CSS a bit more
- [ ] Fix innerDocs
- [ ] Move around the components in a way that makes sense

I can finish these things in this PR, or in a following up one... Whatever you think makes more sense

image

image

### CODE REVIEW

**Comment by josepot** [comment]
Hi @wirednkod !

I don't have the time to review this right now, I will be reviewing it tomorrow morning first thing in the morning, for sure! However, I just wanted to say from the very bottom of my heart: THANK YOU SO MUCH for always being there to lend a hand and being so proactive and helpful!

As I already mentioned: I will be reviewing this properly tomorrow. However, at a first glance I noticed a few things:
- something odd happened with the git history? 🤔
- the following folder `examples/decode-viewer/src/stories/assets/` seems to have a bunch of unnecessary files
- there seems to be 2 metadata files one txt and one json, do you need them both? they are quite heavy.
- in general: could you please make sure that you remove all the unnecessary files? I think that I've seen a couple more, like one mdx file and one react.svg, etc.

Also, I want to say that despite the fact that I would have approached this a bit differently: "done >>>>>>>>> perfect" So, thank you so much! This should already enable us to test some important workflows, so this is awesome! Thanks again!

**Comment by wirednkod** [comment]
I will go through your bullets and update it accordingly. This is just a first draft and we can pivot it to whatever you may want to - just tell me what needed and I can adjust it.

**Comment by wirednkod** [comment]
@josepot I am closing this in favour of #156 - which has a better commit history (apologies for that), a better Readme.md and removed all the unecessery files as per your advice

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-api-2023-q4-update/5318/1

**Pull request closed without merging**
